# The base image for this project
FROM python:3.12-slim AS base

# The image used for development, in docker compose
FROM base AS dev
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=never
ENV VIRTUAL_ENV=/opt/venv
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="/opt/venv/bin:${PATH}"
WORKDIR /app
ARG VERSION=0.0.0
ENV HATCH_VCS_PRETEND_VERSION=$VERSION
ENV SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION
COPY pyproject.toml uv.lock README.md ./
COPY src/smeterd/__init__.py ./src/smeterd/__init__.py
RUN uv sync --locked --group dev

# The image used by ci/cd to lint, test and build the project
FROM dev AS builder
COPY . .
RUN uv run ruff check src/ tests/
RUN uv format --check -- src/ tests/
RUN uv run pytest -vv --no-cov-on-fail --cov=src --cov-report=term --cov-report=html --cov-report=xml
RUN uv build

# Build step to extract the wheel generated by uv build to the host machine (for uploading to pypi)
FROM scratch AS package
COPY --from=builder /app/dist/ /

# The final production image, as minimal as possible
FROM base
RUN --mount=type=bind,from=builder,source=/app/dist,target=/dist pip install /dist/*.whl
